apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: frontend
spec:
  rules:
  - host: "shop.35.246.234.184.nip.io"
    http:
      paths:
      - path: "/"
        backend:
          serviceName: frontend
          servicePort: 80
